---
- name: Install Docker
  hosts: aws_ec2
  become: yes  
  tasks:
    - name: Install Docker
      shell: |
        sudo yum update -y
        sudo yum install -y docker
        sudo systemctl start docker
        sudo systemctl enable docker
    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started

- name: Create new linux user
  hosts: aws_ec2
  become: yes  
  tasks:
    - name: Create new linux user
      user:
        name: user
        groups: adm,docker

- name: Install Docker-compose
  hosts: aws_ec2
  become: yes  
  become_user: user
  tasks:
    - name: Create docker-compose directory
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Install docker-compose
      get_url: 
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ remote_arch.stdout }}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x

- name: Start docker containers
  hosts: aws_ec2
  become: yes  
  become_user: user
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      copy:
        src: /home/mauricio/Documentos/docker-compose.yaml
        dest: /home/user/docker-compose.yaml
    - name: Docker login
      docker_login: 
        username: mauriciocamilo
        password: "{{docker_password}}"
    - name: Start containers from compose
      community.docker.docker_compose_v2: 
        project_src: /home/user
        state: present # Runs docker compose up by default
